# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 324c46bb5766c45cb4406b6bf8dd58abe1e7696f25ec6670845eb41129efad20954a13303343f6988c527daa92878fe988d1aed287496705febb6bf2778f8926

test:
  secret_key_base: 7d6946f13ddca1b7529d6349ac871154a25415bf18896aade394238d959f71e9d6de2e3c145c5a3b67febbeb29b22eccbe95de8ad4bfe8dbbd8321e2118f5127

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
